baseURL = 'https://matt-seb-ho.github.io/msho_website/'
languageCode = 'en-us'
title = 'Matthew Ho'
theme = 'papermod'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'CV'
    url = '/msho_resume.pdf'
    weight = 20
