baseURL = 'https://matt-seb-ho.github.io/msho_website/'
languageCode = 'en-us'
title = 'Matthew Ho'
theme = 'papermod'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'CV'
    # url = '/msho_resume.pdf'
    url = '/msho.pdf'
    weight = 20

# Enable rendering of raw HTML in Markdown content
# note: for coloring text
[markup]
  [markup.goldmark.renderer]
    unsafe = true
